---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-consumer-scaled-object
  namespace: default
  labels:
    deploymentName: rabbitmq-consumer-deployment
spec:
  scaleTargetRef:
    deploymentName: rabbitmq-consumer-deployment
  pollingInterval: 5 # Optional. Default: 30 seconds
  cooldownPeriod: 30 # Optional. Default: 300 seconds
  minReplicaCount: 1 # Optional. Default: 0
  maxReplicaCount: 30 # Optional. Default: 100
  triggers:
    - type: rabbitmq
      metadata:
        queueName: hello
        queueLength: "5"
      authenticationRef:
        name: trigger-auth-rabbitmq-host
